[package]
name = "augmenta-listener"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
axum = { version = "0.7", features = ["macros"] }
axum-macros = { version = "0.4" }
tokio = { version = "1.28", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
